# Generated by Django 4.2.13 on 2024-06-22 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_remove_lead_pdf_file_pdf_pdf_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='pdf_file_name',
            field=models.CharField(default='complications-and-verification-process', max_length=1000),
        ),
    ]
