# Generated by Django 4.2.13 on 2024-06-22 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('has_submenu', models.BooleanField(default=False)),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.page')),
                ('parent_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.menulink')),
            ],
        ),
    ]
