# Generated by Django 4.2.13 on 2024-06-22 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_menulink'),
    ]

    operations = [
        migrations.AddField(
            model_name='menulink',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
