# Generated by Django 4.2.13 on 2024-06-22 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_menulink_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menulink',
            name='parent_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submenus', to='main.menulink'),
        ),
    ]
