# Generated by Django 4.2.13 on 2024-06-22 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_menulink_parent_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='menulink',
            name='separate_url',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menulink',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
