# Generated by Django 4.0 on 2024-06-22 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='logo',
        ),
        migrations.CreateModel(
            name='ClientLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='client_logos/')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logos', to='main.client')),
            ],
        ),
    ]
