# Generated by Django 4.0 on 2024-06-22 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_numbers'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('paragraph', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='numbers',
            name='number',
            field=models.CharField(default='null', max_length=1000),
        ),
    ]
