# Generated by Django 4.0 on 2024-06-22 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('logo', models.ImageField(upload_to='footer_logos/')),
                ('link_text', models.CharField(max_length=200)),
                ('link_url', models.CharField(max_length=200)),
                ('order', models.IntegerField(default=0)),
            ],
        ),
    ]
