# Generated by Django 4.0 on 2024-06-22 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_description', models.CharField(blank=True, max_length=255)),
                ('meta_keywords', models.CharField(blank=True, max_length=255)),
                ('meta_author', models.CharField(blank=True, max_length=100)),
                ('og_title', models.CharField(blank=True, max_length=200)),
                ('og_description', models.CharField(blank=True, max_length=255)),
                ('og_image', models.ImageField(blank=True, upload_to='og_images/')),
                ('pwa_enabled', models.BooleanField(default=False)),
                ('pwa_name', models.CharField(blank=True, max_length=100)),
                ('pwa_short_name', models.CharField(blank=True, max_length=50)),
                ('pwa_description', models.TextField(blank=True)),
                ('pwa_icon', models.ImageField(blank=True, upload_to='pwa_icons/')),
                ('favicon', models.ImageField(blank=True, upload_to='favicons/')),
                ('apple_touch_icon', models.ImageField(blank=True, upload_to='apple_touch_icons/')),
                ('use_keywords', models.BooleanField(default=False)),
                ('keyword_set1_active', models.BooleanField(default=True)),
                ('keyword_set2_active', models.BooleanField(default=False)),
                ('keyword_set3_active', models.BooleanField(default=False)),
                ('custom_head_tags', models.TextField(blank=True, help_text='Enter any custom <head> tags here')),
            ],
        ),
    ]
