# Generated by Django 4.0 on 2024-06-22 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_seo'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('keywords', models.TextField()),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='seo',
            name='keyword_set1_active',
        ),
        migrations.RemoveField(
            model_name='seo',
            name='keyword_set2_active',
        ),
        migrations.RemoveField(
            model_name='seo',
            name='keyword_set3_active',
        ),
        migrations.AddField(
            model_name='seo',
            name='keyword_sets',
            field=models.ManyToManyField(blank=True, related_name='seo_keywords', to='main.KeywordSet'),
        ),
    ]
