# Generated by Django 4.0 on 2024-06-24 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_keywordset_remove_seo_keyword_set1_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seo',
            name='keyword_sets',
        ),
        migrations.RemoveField(
            model_name='seo',
            name='use_keywords',
        ),
        migrations.DeleteModel(
            name='KeywordSet',
        ),
    ]
